

GET http://localhost:3001/api/persons HTTP/1.1


###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "test from rest extension",
    "number" : "898-78-7874"
}


// request to test error handling
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "Filipe Cancelinha",
    "number" : "898-78-7874"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "F",
    "number" : "898-78-7874"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "",
    "number" : ""
}



//testing deployed application - Heroku
###
GET https://boiling-stream-13455.herokuapp.com/api/persons HTTP/1.1

###
POST https://boiling-stream-13455.herokuapp.com/api/persons HTTP/1.1
content-type: application/json

{
    "name" : "Filipe Cancelinha",
    "number" : "898-78-7874"
}

###
DELETE https://boiling-stream-13455.herokuapp.com/api/persons/2561 HTTP/1.1
